# Fonts 
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 10

# Cursor 
cursor #eeeeee
cursor_shape block
cursor_shape_unfocused block

# Colors
foreground #cbe3e7
background #1b182c

background_opacity 0.85
background_blur 0

# The 16 terminal colors
# black
# red
# green
# yellow
# blue
# magenta
# cyan
# white

# Dull colors
color0 #100e23
color1 #ff0050
color2 #95ffa4
color3 #ffe9aa
color4 #425fff
color5 #c991e1
color6 #4dffd8
color7 #cbe3e7

# Bright colors
color8  #565575
color9  #ff5458
color10 #62d196
color11 #ffb378
color12 #659dff
color13 #906cff
color14 #63d1f2
color15 #ffffff
